language: php

php:
  #- 5.3
  - 5.4
  #- 5.5
  #- hhvm

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # configure apache virtual hosts
  - sudo cp -f Build/Travis/VirtualHost /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - echo "127.0.0.1 broensfin.behat" | sudo tee -a /etc/hosts
  - sudo service apache2 restart

  # Create configuration
  - mkdir -p Configuration/Testing/Behat
  - cp Build/Travis/Settings.yaml Configuration/Testing/Behat/Settings.yaml
  - mkdir -p Configuration/Development/Behat
  - cp Build/Travis/Settings.yaml Configuration/Development/Behat/Settings.yaml

  # install
  - composer self-update
  - composer --prefer-source --dev install

  # Set up git
  - git config --global user.email "apocalip@gmail.com"
  - git config --global user.name "Travis"

  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

  # download beard
  - curl -sL https://github.com/mneuhaus/Beard/releases/download/0.8.0/beard-0.8.0.phar > beard.phar
  - chmod +x beard.phar
  - ./beard.phar patch

  # setup up behat
  - php ./flow behat:setup

  # create the database
  - mysql -e 'CREATE DATABASE flow_broensfin_behat;'

  # Warmup Caches
  - FLOW_CONTEXT=Development/Behat ./flow flow:cache:warmup

after_script:
  - mysql -e 'DROP DATABASE flow_broensfin_behat;'

script:
    # - phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
    # - phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
    - bin/behat -c Packages/Sites/Famelo.Broensfin/Tests/Behavior/behat.yml