language: php

php:
  #- 5.3
  - 5.4
  #- 5.5
  #- hhvm

before_script:
    - composer self-update
    - composer --prefer-source --dev install

script:
    - phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
    - phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml

matrix:
  allow_failures:
    php: hhvm
